markets:
  - code: CN
    stocks:
      - symbol: "600519"
        name: "贵州茅台"
        # cost_price: 1800.00
        # quantity: 100
      - symbol: "000001"
        name: "平安银行"

  - code: HK
    stocks:
      - symbol: "00700"
        name: "腾讯控股"
